version: '2'
services:
  dogPals:
    image:  bharatkareti/dogpals_frontend:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=dev,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@52.74.130.214:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@52.74.130.214:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://rds-dogpals.ckeoivf0qlep.ap-southeast-1.rds.amazonaws.com:3306/dogPals?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true'
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '8080:8080'

  DogPalsTraining:
    image: bharatkareti/dogpals_training:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=dev,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@52.74.130.214:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@52.74.130.214:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://rds-dogpals.ckeoivf0qlep.ap-southeast-1.rds.amazonaws.com:3306/dogpalstraining?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true'
      - JHIPSTER_SLEEP=60
      - JHIPSTER_REGISTRY_PASSWORD=admin


  DogPalsForum:
    image:  bharatkareti/dogpals_forum:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=dev,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@52.74.130.214:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@52.74.130.214:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://rds-dogpals.ckeoivf0qlep.ap-southeast-1.rds.amazonaws.com:3306/dogpalsforum?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true'
      - JHIPSTER_SLEEP=50
      - JHIPSTER_REGISTRY_PASSWORD=admin


  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  # jhipster-elasticsearch:
  #   extends:
  #     file: jhipster-console.yml
  #     service: jhipster-elasticsearch
  # jhipster-logstash:
  #   extends:
  #     file: jhipster-console.yml
  #     service: jhipster-logstash
  #   depends_on:
  #     - jhipster-elasticsearch
  # jhipster-console:
  #   extends:
  #     file: jhipster-console.yml
  #     service: jhipster-console
  #   depends_on:
  #     - jhipster-elasticsearch
  # jhipster-import-dashboards:
  #   extends:
  #     file: jhipster-console.yml
  #     service: jhipster-import-dashboards
  #   depends_on:
  #     - jhipster-elasticsearch
